### ISSUE TITLE
I'd like to delete some of the maps I've made.

### ISSUE THREAD

**Issue by willnwhite** [MapBBCode/share.mapbbcode.org#29] opened 2014-07-06 18:19 UTC
They're taking up memory on your web server. I've got the URLs in my browser history.

**Comment by Zverik** [comment] 2015-04-05 22:24
Duplicate of #5, done.

**Closed by Zverik** 2015-04-05 22:24 UTC

**Comment by willnwhite** [comment] 2015-04-07 09:56
Sorry, I meant for non-logged in maps.
